"""cria tabelas de usuarios produtos e alertas de estoque

Revision ID: 04ae02e4998b
Revises: 
Create Date: 2026-08-25 15:36:09.149494
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '04ae02e4998b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('preco', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantidade_em_estoque', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('preco >= 0', name='ck_produtos_preco_nao_negativo'),
    sa.CheckConstraint('quantidade_em_estoque >= 0', name='ck_produtos_estoque_nao_negativo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_produtos_estoque', 'produtos', ['quantidade_em_estoque'], unique=False)
    op.create_index(op.f('ix_produtos_nome'), 'produtos', ['nome'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('alertas_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('produto_nome', sa.String(length=120), nullable=False),
    sa.Column('quantidade_no_momento', sa.Integer(), nullable=False),
    sa.Column('limite_configurado', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(length=30), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_estoque_produto_id'), 'alertas_estoque', ['produto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alertas_estoque_produto_id'), table_name='alertas_estoque')
    op.drop_table('alertas_estoque')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_produtos_nome'), table_name='produtos')
    op.drop_index('ix_produtos_estoque', table_name='produtos')
    op.drop_table('produtos')
    # ### end Alembic commands ###
